FORMAT: 1A
HOST: http://private-6b025-topicmoodtracker.apiary-mock.com/

# topicMoodTracker

topicMoodTracker is an API that will allow one single user to set a basic mood per day regarding to a given topic.
You can therefore create several topics to track your achievement rate in a day basis.

# topicMoodTracker API Root [/]

This resource does not have any attributes. Instead it offers the initial API affordances in the form of the links in the JSON body.

## Retrieve the Entry Point [GET]

+ Response 200 (application/json)

        {
            "topics_url": "/topics"
        }

# Group Topics

Resources related to the topics in the API.

## Topic  [/topics/{topic_id}]

A Topic object has the following attributes:

+ topic
+ created_at - An ISO8601 date when the question was published.
+ url
+ moods - An array of Choice objects.

+ Parameters
    + topic_id 1 (required, number) - ID of the Topic in the form of an integer
        
### Get the detail for a given Topic [GET]

+ Response 200 (application/json)

        {  
            "topic": "How about frying an egg?",
            "created_at": "2016-10-11T10:38:51.620Z",
            "url": "/topics/1",
            "moods": [
                {
                    "mood": "It was really good today",
                    "url": "/topics/1/moods/1",
                    "valoration": "positive",
                    "count": 3
                }, {
                    "mood": "No fried eggs today",
                    "url": "/topics/1/moods/2",
                    "valoration": "neutral",
                    "count": 10
                }, {
                    "mood": "Neither the dog wanted it today"
                    "url": "/topics/1/moods/3",
                    "valoration": "negative",
                    "count": 5
                }
            ]
        }
        
## Moods [/topics/{topic_id}/moods/{mood_id}/day/{day}]

+ Parameters
    + topic_id: 1 (required, number) - ID of the Topic in form of an integer
    + mood_id: 1 (required, number) - ID of the Mood in form of an integer
    + day: An ISO8601 date to track a given mood for a given the topic.
    
### Track a Mood [POST]

This action allows you to track one mood for a topic, at a given day.

+ Response 201

    + Headers

            Location: /topics/1
            
## Moods [/topics/{topic_id}/moods/{mood_id}]

+ Parameters
    + topic_id: 1 (required, number) - ID of the Topic in form of an integer
    + mood_id: 1 (required, number) - ID of the Mood in form of an integer            
            
### Get the detail for a given mood [GET]

+ Response 200 (application/json)
       
        {
            "mood": "It was really good today",
            "url": "topics/1/moods/1",
            "valoration": "positive",
            "count": 3,
            "days": [
                {
                    "tracked_at": "2016-10-21T14:38:51.620Z"
                }, {
                    "tracked_at": "2016-11-03T14:48:51.620Z"
                }, {
                    "tracked_at": "2016-11-04T13:58:51.620Z"
                }
            ]
        }
        
## Topics Collection [/topics{?page}]

+ Parameters
    + page: 1 (optional, number) - The page of questions to return

### List All Topics [GET]

+ Response 200 (application/json)

    + Headers

            Link: </questions?page=2>; rel="next"
            
    + Body

            [
                {
                    "topic": "How about frying an egg?",
                    "created_at": "2016-10-11T10:38:51.620Z",
                    "url": "/topicsr/1",
                    "moods": [
                        {
                            "mood": "It was really good today",
                            "url": "/topics/1/moods/1",
                            "valoration": "positive",
                            "count": 3
                        }, {
                            "mood": "No fried eggs today",
                            "url": "/topics/1/moods/2",
                            "valoration": "neutral",
                            "count": 10
                        }, {
                            "mood": "Neither the dog wanted it today"
                            "url": "/topics/1/moods/3",
                            "valoration": "negative",
                            "count": 5
                        }
                    ]
                }, {
                    "topic": "Have you worked in your arduino car prototype 1?",
                    "created_at": "2016-11-01T08:40:51.620Z",
                    "moods": [
                        {
                            "mood": "oh yes, oh yes",
                            "url": "topics/1/moods/1",
                            "valoration": "positive",
                            "count": 0
                        }, {
                            "mood": "yes/no, im analizying next step",
                            "url": "topics/2/moods/2",
                            "valoration": "neutral",
                            "count": 0
                        }, {
                            "mood":  "who were you and who were arduino, again?",
                            "url": "topics/2/moods/3",
                            "valoration": "negative",
                            "count": 0
                        }
                    ]
                }
            ]

### Create a New Topic [POST]

Create your new topic of interest this action. It takes a JSON
object containing a topic and also the configuration of your 3 moods.

+ topic (string) - The topic you want to track
+ moods (array[moods]) - A collection to configure the moods to choose daily.

+ Request (application/json)

            {
                "topic": "Have you worked in your arduino car prototype 1?",
                "choices": [
                    "positive": "oh yes, oh yes",
                    "neutral": "yes/no, im analizying next step",
                    "negative": "who were you and what were arduino, again?"
                ]
            }

+ Response 201 (application/json)

    + Headers

            Location: /topics/2

    + Body

                {
                    "topic": "Have you worked in your arduino car prototype 1?",
                    "created_at": "2016-11-01T08:40:51.620Z",
                    "url": "topics/2",
                    "moods": [
                        {
                            "mood": "oh yes, oh yes",
                            "url": "topics/2/moods/1",
                            "valoration": "positive",
                            "count": 0
                        }, {
                            "mood": "yes/no, im analizying next step",
                            "url": "topics/2/moods/2",
                            "valoration": "neutral",
                            "count": 0
                        }, {
                            "mood":  "who were you and who were arduino, again?",
                            "url": "topics/2/moods/3",
                            "valoration": "negative",
                            "count": 0
                        }
                    ]
                }

### Delete [DELETE]

+ Response 204