FORMAT: 1A
HOST: http://private-6b025-topicmoodtracker.apiary-mock.com/

# topicMoodTracker

topicMoodTracker is an API that will allow one single user to set a basic mood per day regarding to a given topic.
You can therefore create several topics to track your achievement rate in a day basis.

# topicMoodTracker API Root [/]

This resource does not have any attributes. Instead it offers the initial API affordances in the form of the links in the JSON body.

## Retrieve the Entry Point [GET]

+ Response 200 (application/json)

        {
            "topics_url": "/topics"
        }

# Group Topics

Resources related to the topics in the API.

## Topics Collection [/topics{?page}]

+ Parameters
    + page: 1 (optional, number) - The page of questions to return

### List All Topics [GET]

+ Response 200 (application/json)

    + Headers

            Link: </questions?page=2>; rel="next"

    + Body

            [
                {
                    "id": 1,
                    "topic": "How about frying an egg?",
                    "created_at": "2016-10-11T10:38:51.620Z",
                    "url": "/topics/1",
                    "moods": [
                        {
                            "id": 1,
                            "mood": "It was really good today",
                            "order": 1,
                            "url": "/topics/1/moods/1",
                            "valoration": "positive",
                            "count": 3
                        }, {
                            "id": 2,
                            "mood": "No fried eggs today",
                            "order": 2,
                            "url": "/topics/1/moods/2",
                            "valoration": "neutral",
                            "count": 10
                        }, {
                            "id": 3,
                            "mood": "Neither the dog wanted it today",
                            "order": 3,
                            "url": "/topics/1/moods/3",
                            "valoration": "negative",
                            "count": 5
                        }
                    ]
                }, {
                    "topic": "Have you worked in your arduino car prototype 1?",
                    "created_at": "2016-11-01T08:40:51.620Z",
                    "url": "/topics/1",
                    "moods": [
                        {
                            "id": 4,
                            "mood": "oh yes, oh yes",
                            "order": 1,
                            "url": "topics/2/moods/1",
                            "valoration": "positive",
                            "count": 0
                        }, {
                            "id": 5,
                            "mood": "yes/no, im analizying next step",
                            "order": 2,
                            "url": "topics/2/moods/2",
                            "valoration": "neutral",
                            "count": 0
                        }, {
                            "id": 3,
                            "mood":  "who were you and who were arduino, again?",
                            "order": 3,
                            "url": "topics/2/moods/3",
                            "valoration": "negative",
                            "count": 0
                        }
                    ]
                }
            ]

### Create a New Topic [POST]

Create your new topic of interest this action. It takes a JSON
object containing a topic and also the configuration of your 3 moods.

+ topic (string) - The topic you want to track
+ moods (array[moods]) - A collection to configure the moods to choose daily.

+ Request (application/json)

            {
                "topic": "Have you worked in your arduino car prototype 1?",
                "moods": [
                    {
                        "mood": "oh yes, oh yes",
                        "order": 1,
                        "valoration": "positive"
                    }, {
                        "mood": "yes/no, im analizying next step",
                        "order": 2,
                        "valoration": "positive"
                    }, {
                        "mood": "who were you and what were arduino, again?",
                        "order": 3,
                        "valoration": "positive"
                    }
                ]
            }

+ Response 201 (application/json)

    + Headers

            Location: /topics/2

### Delete [DELETE]

+ Response 204

## Topic  [/topics/{topic_id}]

A Topic object has the following attributes:

+ id
+ topic
+ created_at - An ISO8601 date when the question was published.
+ moods - An array of moods objects.

+ Parameters
    + topic_id: 1 (required, number) - ID of the Topic in the form of an integer
        
### Get the detail for a given Topic [GET]

+ Response 200 (application/json)

        {
            "id": 1
            "topic": "How about frying something?",
            "created_at": "2016-10-11T10:38:51.620Z",
            "url": "/topics/1",
            "moods": [
                {
                    "id": 1,
                    "mood": "It was really good today",
                    "order": 1,
                    "url": "/topics/1/moods/1",
                    "valoration": "positive",
                    "count": 3
                }, {
                    "id": 2,
                    "mood": "No, I wasnt on the mood of cooking today",
                    "order": 2,
                    "url": "/topics/1/moods/2",
                    "valoration": "neutral",
                    "count": 10
                }, {
                    "id": 3,
                    "mood": "Neither the dog wanted it today",
                    "order": 3,
                    "url": "/topics/1/moods/3",
                    "valoration": "negative",
                    "count": 5
                }
            ]
        }


### Update a given Topic [PUT]

+ Request (application/json)

        {
            "id": 1
            "topic": "How about frying an egg?",
            "created_at": "2016-10-11T10:38:51.620Z",
            "moods": [
                {
                    "id": 1,
                    "mood": "It was really good today",
                    "order": 1,
                    "valoration": "positive",
                }, {
                    "id": 2,
                    "mood": "No fried eggs today",
                    "order": 2,
                    "valoration": "neutral",
                }, {
                    "id": 3,
                    "mood": "Neither the dog wanted it today",
                    "order": 3,
                    "valoration": "negative",
                }
            ]
        }

+ Response 201

    + Headers

            Location: /topics/1


## Moods [/topics/{topic_id}/moods/{mood_order}]

+ Parameters
    + topic_id: 1 (required, number) - ID of the Topic in form of an integer
    + mood_order: 1 (required, number) - Order of the Mood within its topic in form of an integer

### Track a Mood [PATCH]

This action allows you to track one mood for a topic, at a given day.

+ Request

        {
            day: "2016-10-21T14:38:51.620Z"
        }

+ Response 201

    + Headers

            Location: /topics/1/moods/2

### Get the detail for a given mood [GET]

+ Response 200 (application/json)
       
        {                    
            "id": 1,
            "mood": "It was really good today",
            "order": 1,
            "url": "topics/1/moods/1",
            "valoration": "positive",
            "count": 3,
            "trackings": [
                {
                    "id": 1,
                    "tracked_at": "2016-10-21T14:38:51.620Z"
                }, {
                    "id": 2,
                    "tracked_at": "2016-11-03T14:48:51.620Z"
                }, {
                    "id": 3,
                    "tracked_at": "2016-11-04T13:58:51.620Z"
                }
            ]
        }