# Data Structures

## Topic (object)
+ id: 1 (number, required)
+ description: Have you worked in your arduino car prototype 1?, (string, required)

## Mood (object)
+ id: 1 (number, required)
+ rating: positive, neutral, negative (choice list, required)
+ picture: happy.png (string, required)
+ description: I made it (string, required)